[package]
name = "kiss_dc"
version = "0.0.5"
authors = ["Konrad Podstawki"]
edition = "2018"
description = "A tool for simple communication with a computing server using the KISS rule."
license = "Beerware"

[dependencies]
tungstenite = "0.11.1"
